-- Definir as cardinalidades máximas e mínimas 
-- RESPOSTA: cardinalidades.png

-- Criar o esquema do banco e apresentar o DDL utilizado
-- RESPOSTA: ddl.sql


-- Apresentar o SQL para as seguintes consultas
  * Atores do filme com título “XYZ”
  * Filmes que o ator de nome “FULANO” participou
  * Listar os filmes do ano 2015 ordenados pelo quantidade de atores participantes e pelo título em ordem alfabética.
  * Listar os atores que trabalharam em filmes cujo diretor foi “SPIELBERG”